---
title: "Another Puzzle: Deadly Board Game"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/cloud/project/Bukan Infografis/puzzles/Puzzle Deadly Blocks")
rm(list=ls())
library(dplyr)
library(ggplot2)
library(ggthemes)
library(ggpubr)
```

Sudah baca _puzzles_ saya sebelumnya di [sana](https://ikanx101.github.io/blog/puzzle-usia/) dan [sini](https://ikanx101.github.io/blog/elevator-problem/)?

Dua _puzzles_ tersebut adalah beberapa contoh aplikasi simulasi __Monte Carlo__ untuk menyelesaikan masalah _real_.

Sekarang, saya punya _puzzle_ lagi. Begini ceritanya:

____

> Suatu waktu, saya mengunjungi Kerajaan Wakanda. Singkat cerita, saya dituduh melakukan kejahatan. Saya diberikan kesempatan untuk lolos dari hukuman jika mau bermain dalam _deadly board game_.

Bagaimana cara bermainnya:

* _Board_ berisi kotak bernomor dari satu hingga tiga puluh secara berurutan.
  * Kota nol menjadi posisi awal saya.
* Saya diberikan:
  * Tiga koin.
  * Satu dadu.
  * Satu bidak.
* Saya harus memilih dan menaruh tiga koin di tiga kotak berbeda. 
  * Setelah menaruh koin, saya tidak diperbolehkan untuk mengubahnya. 
* Lalu saya diharusnya melempar dadu.
  * Saya akan memindahkan bidak sesuai dengan angka yang keluar di dadu. 
  * Proses ini terus berulang hingga selesai tiga puluh kotak dilalui oleh bidak saya.
* Seandainya dalam seluruh proses ini, bidak saya __tidak pernah sama sekali berhenti di kotak yang memiliki koin__, maka saya akan dieksekusi. 
  * Kebalikannya, jika dalam seluruh prosesnya bidak saya pernah minimal sekali berhenti di kotak yang memiliki koin, maka saya selamat.
  
____

## Pertanyaannya:

> Di kotak nomor berapa saja saya harus menaruh koin?