---
title: "Report Market Share"
subtitle: "Dipersiapkan untuk Sales"
author: "@mr.ikanx"
date: "July 17, 2020"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: 
        collapsed: false
    number_sections: true
    theme: flatly
    highlight: tango
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
setwd("~/Documents/belajaR/Materi Training/Intro to RMD")
load('data contoh.rda')

library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggthemes)

```

# Market Size per Parent 2014 - 2018

Berikut adalah grafik tren market size dari masing-masing parent:

```{r}
data %>% 
  group_by(parent,tahun) %>% 
  summarise(market_size = sum(value)) %>% 
  ungroup() %>% 
  mutate(label = market_size / 1000000000,
         label = round(label,1),
         label = paste0('Rp',label,'Milliar')) %>% 
  ggplot(aes(x = tahun,
             y = market_size)) +
  geom_line(aes(color = parent)) +
  geom_label(aes(label = label,color = parent),size=3) +
  theme_economist()

```


