---
title: "FAEDAH TIDYTEXT di R: Screening Peserta Webinar"
output: github_document
---

```{r setup, include=FALSE}
setwd("~/Documents/belajaR/Bukan Infografis/Matchmaking Event")
library(nomnoml)
knitr::opts_chunk$set(echo = TRUE)
```

# _Preface_

Di suatu pagi yang cerah, sebelum memulai __WFH__, ponsel saya berdering. Muncul pesan masuk dari kawan lama saya. Kalau dipikir-pikir lagi, dunia saya dan dirinya sangat berbeda jauh. Hampir tidak ada irisannya sama sekali. Dirinya bergerak di bidang _event organizer_ khusus _training webinar_ yang lagi naik daun di masa __WFH__ sekarang dan saya bergerak di bidang data.

> Saya dengar dirimu ngasih _training_ __R__ yah? Kata si _xxx_, dirimu bisa melakukan _filtering_ macem-macem di _excel_ yah? Si _xxx_ bilang ke saya, kayaknya dirimu bisa menyelesaikan masalah saya!

Pertama agak kaget dan tersanjung atas kalimat yang dilontarkan rekan saya tersebut. Kaget karena saya sebenarnya juga gak kenal dengan si __xxx__ dan tersanjung karena dari cerita singkatnya, _It is sounds like I am a magician_.

Jadi begini ceritanya:

Teman saya tersebut membuat _scheduled webinar_ untuk _targeted and selected person_. Dia ingin membuat _webinar_ untuk para _manager_ bidang tertentu dari beberapa perusahaan tertentu. Jadi sebenarnya yang ditarget adalah nama-nama perusahaan tertentu. Dia menginformasikan setidaknya ada `100` nama perusahaan. Namun, yang terjadi adalah jumlah pendaftar meledak hingga `4.000` orang yang berasal dari perusahaan lainnya dan universitas.

> Bisa bantu saya _filterin_ siapa saja yang harus masuk ke webinarnya gak? Soalnya _form online_ pendaftarannya itu semuanya dibuat dalam __input text__. Saya udah pusing nih ngefilternya...

Begitu keluh kesahnya.

Usut punya usut, ternyata _event_ tersebut akan diadakan esok pagi. Nah lho...!

# _Challenge_

Tanpa berjanji yang muluk-muluk, saya sampaikan kepada kawan saya tersebut untuk memberikan daftar perusahaan target dan data pendaftar _webinar_ yang dia miliki.

Dalam sekejap, email tersebut masuk dan saya coba lihat sekilas.

Catatan: untuk merahasiakan identitas pihak-pihak terkait, cerita ini didramatisir secukupnya.